version: "3.7"

services:
  database_jrentregas:
    image: postgres
    container_name: database_jrentregas
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=host
      - POSTGRES_DB=jrentregasdb
    volumes:
      - pgdata:/data/postgres 

  app:
    build: .
    container_name: jrentregas
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - database_jrentregas  
    depends_on: 
      - database_jrentregas

volumes:
  pgdata:
    driver: local